LocationTag.create!([
  {ang_list_id: 2687, name: "slovakia", display_name: "Slovakia", process_status: 0, processed_users: nil, statistic_users: 127, last_page: 2},
  {ang_list_id: 2397, name: "latvia", display_name: "Latvia", process_status: 0, processed_users: nil, statistic_users: 186, last_page: 4},
  {ang_list_id: 2369, name: "slovenia", display_name: "Slovenia", process_status: 0, processed_users: nil, statistic_users: 245, last_page: 4},
  {ang_list_id: 2194, name: "bulgaria", display_name: "Bulgaria", process_status: 0, processed_users: nil, statistic_users: 348, last_page: 6},
  {ang_list_id: 2163, name: "hungary", display_name: "Hungary", process_status: 0, processed_users: nil, statistic_users: 359, last_page: 6},
  {ang_list_id: 2006, name: "netherlands", display_name: "Netherlands", process_status: 0, processed_users: nil, statistic_users: 1913, last_page: 0},
  {ang_list_id: 1921, name: "czech republic", display_name: "Czech Republic", process_status: 0, processed_users: nil, statistic_users: 426, last_page: 6},
  {ang_list_id: 1830, name: "poland", display_name: "Poland", process_status: 0, processed_users: nil, statistic_users: 852, last_page: 2},
  {ang_list_id: 1824, name: "romania", display_name: "Romania", process_status: 0, processed_users: nil, statistic_users: 652, last_page: 8},
  {ang_list_id: 1782, name: "united kingdom", display_name: "United Kingdom", process_status: 0, processed_users: nil, statistic_users: 11439, last_page: 0},
  {ang_list_id: 1741, name: "lithuania", display_name: "Lithuania", process_status: 0, processed_users: nil, statistic_users: 195, last_page: 4},
  {ang_list_id: 1717, name: "france", display_name: "France", process_status: 0, processed_users: nil, statistic_users: 3643, last_page: 0},
  {ang_list_id: 1716, name: "germany", display_name: "Germany", process_status: 0, processed_users: nil, statistic_users: 4153, last_page: 0},
  {ang_list_id: 1641, name: "estonia", display_name: "Estonia", process_status: 0, processed_users: nil, statistic_users: 306, last_page: 6},
  {ang_list_id: 174049, name: "presov", display_name: "Presov", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 126209, name: "komarno", display_name: "Komarno", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 119236, name: "humenne", display_name: "Humenne", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 104376, name: "zilina", display_name: "Zilina", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 85084, name: "kosice", display_name: "Kosice", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 79258, name: "trnava", display_name: "Trnava", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 14603, name: "bratislava", display_name: "Bratislava", process_status: 0, processed_users: nil, statistic_users: 78, last_page: 0},
  {ang_list_id: 125036, name: "jelgava", display_name: "Jelgava", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 107430, name: "valmiera", display_name: "Valmiera", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 93210, name: "liepaja", display_name: "Liepaja", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 10672, name: "riga", display_name: "Riga", process_status: 0, processed_users: nil, statistic_users: 135, last_page: 0},
  {ang_list_id: 171365, name: "koper", display_name: "Koper", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 167467, name: "solkan", display_name: "Solkan", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 135214, name: "ljutomer", display_name: "Ljutomer", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 130764, name: "menges", display_name: "Menges", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 87335, name: "novo mesto", display_name: "Novo Mesto", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 85079, name: "maribor", display_name: "Maribor", process_status: 0, processed_users: nil, statistic_users: 15, last_page: 0},
  {ang_list_id: 84523, name: "ptuj", display_name: "Ptuj", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 36769, name: "kranj", display_name: "Kranj", process_status: 0, processed_users: nil, statistic_users: 6, last_page: 0},
  {ang_list_id: 2370, name: "ljubljana", display_name: "Ljubljana", process_status: 0, processed_users: nil, statistic_users: 136, last_page: 0},
  {ang_list_id: 130589, name: "razgrad", display_name: "Razgrad", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 105234, name: "ruse", display_name: "Ruse", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 99707, name: "bansko", display_name: "Bansko", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 92215, name: "sevlievo", display_name: "Sevlievo", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 86653, name: "burgas", display_name: "Burgas", process_status: 0, processed_users: nil, statistic_users: 7, last_page: 0},
  {ang_list_id: 82594, name: "varna", display_name: "Varna", process_status: 0, processed_users: nil, statistic_users: 15, last_page: 0},
  {ang_list_id: 80687, name: "blagoevgrad", display_name: "Blagoevgrad", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 48497, name: "plovdiv", display_name: "Plovdiv", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 2195, name: "sofia", display_name: "Sofia", process_status: 0, processed_users: nil, statistic_users: 274, last_page: 0},
  {ang_list_id: 173104, name: "vac", display_name: "Vac", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 161387, name: "isaszeg", display_name: "Isaszeg", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 123107, name: "zalaszentgrot", display_name: "Zalaszentgrot", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 106770, name: "hodmezovasarhely", display_name: "Hodmezovasarhely", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 83641, name: "balatonalmadi", display_name: "Balatonalmadi", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 82085, name: "budaors", display_name: "Budaors", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 43116, name: "szeged", display_name: "Szeged", process_status: 0, processed_users: nil, statistic_users: 7, last_page: 0},
  {ang_list_id: 2164, name: "budapest", display_name: "Budapest", process_status: 0, processed_users: nil, statistic_users: 291, last_page: 0},
  {ang_list_id: 179804, name: "doesburg", display_name: "Doesburg", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 168548, name: "meppel", display_name: "Meppel", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 165844, name: "heerhugowaard", display_name: "Heerhugowaard", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 138765, name: "gennep", display_name: "Gennep", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 138523, name: "alphen", display_name: "Alphen", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 101230, name: "oirschot", display_name: "Oirschot", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 100880, name: "heerlen", display_name: "Heerlen", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 98366, name: "zelhem", display_name: "Zelhem", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 94882, name: "boxtel", display_name: "Boxtel", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 94311, name: "naarden", display_name: "Naarden", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 93793, name: "dordrecht", display_name: "Dordrecht", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 93001, name: "oss", display_name: "Oss", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 92463, name: "noordwijkerhout", display_name: "Noordwijkerhout", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 91494, name: "arnhem", display_name: "Arnhem", process_status: 0, processed_users: nil, statistic_users: 5, last_page: 0},
  {ang_list_id: 89745, name: "soest, netherlands", display_name: "Soest, Netherlands", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 89632, name: "noordwijk", display_name: "Noordwijk", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 88562, name: "breukelen", display_name: "Breukelen", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 88472, name: "nijmegen", display_name: "Nijmegen", process_status: 0, processed_users: nil, statistic_users: 11, last_page: 0},
  {ang_list_id: 88037, name: "houten", display_name: "Houten", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 87787, name: "epe, netherlands", display_name: "Epe, Netherlands", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 86265, name: "venlo", display_name: "Venlo", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 85605, name: "zwolle", display_name: "Zwolle", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 83912, name: "tilburg", display_name: "Tilburg", process_status: 0, processed_users: nil, statistic_users: 9, last_page: 0},
  {ang_list_id: 83839, name: "leeuwarden", display_name: "Leeuwarden", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 83749, name: "zoetermeer", display_name: "Zoetermeer", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 83648, name: "kampen", display_name: "Kampen", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 83618, name: "enschede", display_name: "Enschede", process_status: 0, processed_users: nil, statistic_users: 11, last_page: 0},
  {ang_list_id: 81847, name: "uden", display_name: "Uden", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 81449, name: "amersfoort", display_name: "Amersfoort", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 80185, name: "ede, netherlands", display_name: "Ede, Netherlands", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 79275, name: "bussum", display_name: "Bussum", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 76965, name: "aalburg", display_name: "Aalburg", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 59296, name: "leiden", display_name: "Leiden", process_status: 0, processed_users: nil, statistic_users: 13, last_page: 0},
  {ang_list_id: 57527, name: "almere", display_name: "Almere", process_status: 0, processed_users: nil, statistic_users: 5, last_page: 0},
  {ang_list_id: 46568, name: "alkmaar", display_name: "Alkmaar", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 42603, name: "huizen", display_name: "Huizen", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 37170, name: "amstelveen", display_name: "Amstelveen", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 32737, name: "hilversum", display_name: "Hilversum", process_status: 0, processed_users: nil, statistic_users: 5, last_page: 0},
  {ang_list_id: 29057, name: "groningen", display_name: "Groningen", process_status: 0, processed_users: nil, statistic_users: 33, last_page: 0},
  {ang_list_id: 25706, name: "maastricht", display_name: "Maastricht", process_status: 0, processed_users: nil, statistic_users: 24, last_page: 0},
  {ang_list_id: 12952, name: "rotterdam", display_name: "Rotterdam", process_status: 0, processed_users: nil, statistic_users: 111, last_page: 0},
  {ang_list_id: 12005, name: "haarlem", display_name: "Haarlem", process_status: 0, processed_users: nil, statistic_users: 17, last_page: 0},
  {ang_list_id: 8879, name: "eindhoven", display_name: "Eindhoven", process_status: 0, processed_users: nil, statistic_users: 52, last_page: 0},
  {ang_list_id: 8752, name: "breda", display_name: "Breda", process_status: 0, processed_users: nil, statistic_users: 14, last_page: 0},
  {ang_list_id: 2616, name: "the hague", display_name: "The Hague", process_status: 0, processed_users: nil, statistic_users: 52, last_page: 0},
  {ang_list_id: 2147, name: "utrecht", display_name: "Utrecht", process_status: 0, processed_users: nil, statistic_users: 66, last_page: 0},
  {ang_list_id: 2103, name: "delft", display_name: "Delft", process_status: 0, processed_users: nil, statistic_users: 31, last_page: 0},
  {ang_list_id: 1771, name: "amsterdam", display_name: "Amsterdam", process_status: 0, processed_users: nil, statistic_users: 1137, last_page: 0},
  {ang_list_id: 174950, name: "dubi", display_name: "Dubi", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 161476, name: "jesenice, czech republic", display_name: "Jesenice, Czech Republic", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 117200, name: "cesky krumlov", display_name: "Cesky Krumlov", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 99768, name: "sternberk", display_name: "Sternberk", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 86364, name: "hradec kralove", display_name: "Hradec Kralove", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 81791, name: "plzen", display_name: "Plzen", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 81329, name: "olomouc", display_name: "Olomouc", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 80712, name: "ostrava", display_name: "Ostrava", process_status: 0, processed_users: nil, statistic_users: 14, last_page: 0},
  {ang_list_id: 40384, name: "jablonec", display_name: "Jablonec", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 31313, name: "ceske budejovice", display_name: "Ceske Budejovice", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 20427, name: "brno", display_name: "Brno", process_status: 0, processed_users: nil, statistic_users: 38, last_page: 0},
  {ang_list_id: 2150, name: "prague", display_name: "Prague", process_status: 0, processed_users: nil, statistic_users: 303, last_page: 0},
  {ang_list_id: 165253, name: "pabianice", display_name: "Pabianice", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 158826, name: "tarnow", display_name: "Tarnow", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 157721, name: "sosnowiec", display_name: "Sosnowiec", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 135658, name: "rzeszow", display_name: "Rzeszow", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 134416, name: "torun", display_name: "Torun", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 114292, name: "gorzow wielkopolski", display_name: "Gorzow Wielkopolski", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 112522, name: "ruda slaska", display_name: "Ruda Slaska", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 108031, name: "zakopane", display_name: "Zakopane", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 107786, name: "polaniec", display_name: "Polaniec", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 92089, name: "jawor", display_name: "Jawor", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 91019, name: "opole", display_name: "Opole", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 86372, name: "zielona gora", display_name: "Zielona Gora", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 82082, name: "katowice", display_name: "Katowice", process_status: 0, processed_users: nil, statistic_users: 11, last_page: 0},
  {ang_list_id: 82057, name: "gdynia", display_name: "Gdynia", process_status: 0, processed_users: nil, statistic_users: 11, last_page: 0},
  {ang_list_id: 57928, name: "cracow", display_name: "Cracow", process_status: 0, processed_users: nil, statistic_users: 36, last_page: 0},
  {ang_list_id: 21181, name: "szczecin", display_name: "Szczecin", process_status: 0, processed_users: nil, statistic_users: 10, last_page: 0},
  {ang_list_id: 20068, name: "gliwice", display_name: "Gliwice", process_status: 0, processed_users: nil, statistic_users: 8, last_page: 0},
  {ang_list_id: 3009, name: "poznan", display_name: "Poznan", process_status: 0, processed_users: nil, statistic_users: 69, last_page: 0},
  {ang_list_id: 2705, name: "warsaw", display_name: "Warsaw", process_status: 0, processed_users: nil, statistic_users: 325, last_page: 0},
  {ang_list_id: 1829, name: "gdansk", display_name: "Gdansk", process_status: 0, processed_users: nil, statistic_users: 35, last_page: 0},
  {ang_list_id: 1772, name: "krakow", display_name: "Krakow", process_status: 0, processed_users: nil, statistic_users: 112, last_page: 0},
  {ang_list_id: 162619, name: "toplita", display_name: "Toplita", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 160898, name: "focsani", display_name: "Focsani", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 140167, name: "otopeni", display_name: "Otopeni", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 135022, name: "sovata", display_name: "Sovata", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 126634, name: "galati", display_name: "Galati", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 126372, name: "miercurea-ciuc", display_name: "Miercurea-ciuc", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 103625, name: "targu-mures", display_name: "Targu-mures", process_status: 0, processed_users: nil, statistic_users: 6, last_page: 0},
  {ang_list_id: 98107, name: "ramnicu valcea", display_name: "Ramnicu Valcea", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 91699, name: "baia mare", display_name: "Baia Mare", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 91181, name: "oradea", display_name: "Oradea", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 85896, name: "alexandria, romania", display_name: "Alexandria, Romania", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 85291, name: "floresti, romania", display_name: "Floresti, Romania", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 85272, name: "brasov", display_name: "Brasov", process_status: 0, processed_users: nil, statistic_users: 10, last_page: 0},
  {ang_list_id: 82694, name: "constanta", display_name: "Constanta", process_status: 0, processed_users: nil, statistic_users: 8, last_page: 0},
  {ang_list_id: 82146, name: "bucuresci", display_name: "Bucuresti", process_status: 0, processed_users: nil, statistic_users: 10, last_page: 0},
  {ang_list_id: 74547, name: "timisoara", display_name: "Timisoara", process_status: 0, processed_users: nil, statistic_users: 31, last_page: 0},
  {ang_list_id: 54589, name: "bacau", display_name: "Bacau", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 47024, name: "arad", display_name: "Arad", process_status: 0, processed_users: nil, statistic_users: 7, last_page: 0},
  {ang_list_id: 37153, name: "sfintesti", display_name: "Sfintesti", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 30097, name: "ploiesti", display_name: "Ploiesti", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 27639, name: "sibiu", display_name: "Sibiu", process_status: 0, processed_users: nil, statistic_users: 8, last_page: 0},
  {ang_list_id: 26821, name: "bistrita", display_name: "Bistrita", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 26064, name: "iasi", display_name: "Iasi", process_status: 0, processed_users: nil, statistic_users: 35, last_page: 0},
  {ang_list_id: 12238, name: "craiova", display_name: "Craiova", process_status: 0, processed_users: nil, statistic_users: 7, last_page: 0},
  {ang_list_id: 9076, name: "cluj-napoca", display_name: "Cluj-napoca", process_status: 0, processed_users: nil, statistic_users: 94, last_page: 0},
  {ang_list_id: 1779, name: "bucharest", display_name: "Bucharest", process_status: 0, processed_users: nil, statistic_users: 313, last_page: 0},
  {ang_list_id: 179893, name: "matlock", display_name: "Matlock", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 175133, name: "brentwood, united kingdom", display_name: "Brentwood, United Kingdom", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 172588, name: "carmarthen", display_name: "Carmarthen", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 172341, name: "accrington", display_name: "Accrington", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 169636, name: "spalding", display_name: "Spalding", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 168395, name: "cupar", display_name: "Cupar", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 164854, name: "northallerton", display_name: "Northallerton", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 164717, name: "braintree", display_name: "Braintree", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 160404, name: "douglas, united kingdom", display_name: "Douglas, United Kingdom", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 157035, name: "portadown", display_name: "Portadown", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 138024, name: "burgess hill", display_name: "Burgess Hill", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 137993, name: "rochester, united kingdom", display_name: "Rochester, United Kingdom", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 134751, name: "worthing", display_name: "Worthing", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 130145, name: "kilmarnock", display_name: "Kilmarnock", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 126252, name: "southport", display_name: "Southport", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 125203, name: "reigate", display_name: "Reigate", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 124199, name: "stirling", display_name: "Stirling", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 123876, name: "abingdon", display_name: "Abingdon", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 121207, name: "heswall", display_name: "Heswall", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 117963, name: "macclesfield", display_name: "Macclesfield", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 115310, name: "welwyn garden city", display_name: "Welwyn Garden City", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 115164, name: "rugby", display_name: "Rugby", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 113428, name: "torquay", display_name: "Torquay", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 110963, name: "fareham", display_name: "Fareham", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 104847, name: "aberdare", display_name: "Aberdare", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 100977, name: "castle douglas", display_name: "Castle Douglas", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 100549, name: "solihull", display_name: "Solihull", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 98200, name: "sevenoaks", display_name: "Sevenoaks", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 97629, name: "new deer", display_name: "New Deer", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 96617, name: "loughton", display_name: "Loughton", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 96578, name: "bicester", display_name: "Bicester", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 96071, name: "keighley", display_name: "Keighley", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 95846, name: "sittingbourne", display_name: "Sittingbourne", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 93851, name: "haywards heath", display_name: "Haywards Heath", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 93122, name: "wolverhampton", display_name: "Wolverhampton", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 92971, name: "ashford", display_name: "Ashford", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 92756, name: "dumbarton", display_name: "Dumbarton", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 92322, name: "stafford", display_name: "Stafford", process_status: 0, processed_users: nil, statistic_users: 6, last_page: 0},
  {ang_list_id: 91605, name: "high wycombe", display_name: "High Wycombe", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 90348, name: "ayr", display_name: "Ayr", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 90129, name: "hove", display_name: "Hove", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 88860, name: "letchworth", display_name: "Letchworth", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 88859, name: "corby", display_name: "Corby", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 88669, name: "borehamwood", display_name: "Borehamwood", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 88025, name: "wellingborough", display_name: "Wellingborough", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 87965, name: "luton", display_name: "Luton", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 87327, name: "stamford, united kingdom", display_name: "Stamford, United Kingdom", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 87104, name: "paisley", display_name: "Paisley", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 87057, name: "bedford", display_name: "Bedford", process_status: 0, processed_users: nil, statistic_users: 5, last_page: 0},
  {ang_list_id: 87009, name: "chatham", display_name: "Chatham", process_status: 0, processed_users: nil, statistic_users: 9, last_page: 0},
  {ang_list_id: 86752, name: "royal tunbridge wells", display_name: "Royal Tunbridge Wells", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 85703, name: "preston", display_name: "Preston", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 85306, name: "wokingham", display_name: "Wokingham", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 85266, name: "halifax, united kingdom", display_name: "Halifax, United Kingdom", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 85215, name: "wallasey", display_name: "Wallasey", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 85097, name: "washington, united kingdom", display_name: "Washington, United Kingdom", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 84875, name: "sleaford", display_name: "Sleaford", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 84852, name: "kettering, united kingdom", display_name: "Kettering, United Kingdom", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 84615, name: "grimsby", display_name: "Grimsby", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 84097, name: "bangor", display_name: "Bangor", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 83666, name: "darlington", display_name: "Darlington", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 83513, name: "loughborough", display_name: "Loughborough", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 82977, name: "chichester", display_name: "Chichester", process_status: 0, processed_users: nil, statistic_users: 7, last_page: 0},
  {ang_list_id: 82687, name: "portsmouth", display_name: "Portsmouth", process_status: 0, processed_users: nil, statistic_users: 11, last_page: 0},
  {ang_list_id: 82385, name: "littlehampton", display_name: "Littlehampton", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 82361, name: "colchester", display_name: "Colchester", process_status: 0, processed_users: nil, statistic_users: 7, last_page: 0},
  {ang_list_id: 81859, name: "maidenhead", display_name: "Maidenhead", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 81843, name: "rotherham", display_name: "Rotherham", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 81243, name: "gateshead", display_name: "Gateshead", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 81107, name: "wakefield", display_name: "Wakefield", process_status: 0, processed_users: nil, statistic_users: 7, last_page: 0},
  {ang_list_id: 81027, name: "royal leamington spa", display_name: "Royal Leamington Spa", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 80798, name: "fleet", display_name: "Fleet", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 80796, name: "basingstoke", display_name: "Basingstoke", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 79729, name: "newport, united kingdom", display_name: "Newport, United Kingdom", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 78773, name: "lichfield", display_name: "Lichfield", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 78542, name: "truro", display_name: "Truro", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 77758, name: "northampton", display_name: "Northampton", process_status: 0, processed_users: nil, statistic_users: 11, last_page: 0},
  {ang_list_id: 73387, name: "newbury", display_name: "Newbury", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 73016, name: "ipswich", display_name: "Ipswich", process_status: 0, processed_users: nil, statistic_users: 5, last_page: 0},
  {ang_list_id: 71733, name: "blackburn", display_name: "Blackburn", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 71014, name: "staines", display_name: "Staines", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 70962, name: "huddersfield", display_name: "Huddersfield", process_status: 0, processed_users: nil, statistic_users: 5, last_page: 0},
  {ang_list_id: 59895, name: "salisbury", display_name: "Salisbury", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 59301, name: "aylesbury", display_name: "Aylesbury", process_status: 0, processed_users: nil, statistic_users: 6, last_page: 0},
  {ang_list_id: 58725, name: "chelmsford", display_name: "Chelmsford", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 56591, name: "lincoln, united kingdom", display_name: "Lincoln, United Kingdom", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 55166, name: "newry", display_name: "Newry", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 54220, name: "worcester, united kingdom", display_name: "Worcester, United Kingdom", process_status: 0, processed_users: nil, statistic_users: 6, last_page: 0},
  {ang_list_id: 51683, name: "blackpool", display_name: "Blackpool", process_status: 0, processed_users: nil, statistic_users: 5, last_page: 0},
  {ang_list_id: 48917, name: "middlesbrough", display_name: "Middlesbrough", process_status: 0, processed_users: nil, statistic_users: 7, last_page: 0},
  {ang_list_id: 45303, name: "harrogate", display_name: "Harrogate", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 44688, name: "gloucester", display_name: "Gloucester", process_status: 0, processed_users: nil, statistic_users: 5, last_page: 0},
  {ang_list_id: 44481, name: "scarborough", display_name: "Scarborough", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 43216, name: "taunton", display_name: "Taunton", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 42062, name: "milton keynes", display_name: "Milton Keynes", process_status: 0, processed_users: nil, statistic_users: 27, last_page: 0},
  {ang_list_id: 40401, name: "londonderry", display_name: "Londonderry", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 39391, name: "swindon", display_name: "Swindon", process_status: 0, processed_users: nil, statistic_users: 7, last_page: 0},
  {ang_list_id: 38865, name: "doncaster", display_name: "Doncaster", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 36744, name: "plymouth", display_name: "Plymouth", process_status: 0, processed_users: nil, statistic_users: 15, last_page: 0},
  {ang_list_id: 36221, name: "slough", display_name: "Slough", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 34089, name: "swansea", display_name: "Swansea", process_status: 0, processed_users: nil, statistic_users: 10, last_page: 0},
  {ang_list_id: 31056, name: "bolton", display_name: "Bolton", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 30890, name: "warrington", display_name: "Warrington", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 30348, name: "andover, united kingdom", display_name: "Andover, United Kingdom", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 28572, name: "dundee", display_name: "Dundee", process_status: 0, processed_users: nil, statistic_users: 12, last_page: 0},
  {ang_list_id: 27990, name: "reading", display_name: "Reading", process_status: 0, processed_users: nil, statistic_users: 39, last_page: 0},
  {ang_list_id: 27618, name: "liverpool", display_name: "Liverpool", process_status: 0, processed_users: nil, statistic_users: 29, last_page: 0},
  {ang_list_id: 27018, name: "chester", display_name: "Chester", process_status: 0, processed_users: nil, statistic_users: 13, last_page: 0},
  {ang_list_id: 24558, name: "aberdeen", display_name: "Aberdeen", process_status: 0, processed_users: nil, statistic_users: 11, last_page: 0},
  {ang_list_id: 23538, name: "canterbury", display_name: "Canterbury", process_status: 0, processed_users: nil, statistic_users: 11, last_page: 0},
  {ang_list_id: 22454, name: "stoke-on-trent", display_name: "Stoke-on-trent", process_status: 0, processed_users: nil, statistic_users: 6, last_page: 0},
  {ang_list_id: 22111, name: "warwick, united kingdom", display_name: "Warwick, United Kingdom", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 21989, name: "winchester", display_name: "Winchester", process_status: 0, processed_users: nil, statistic_users: 9, last_page: 0},
  {ang_list_id: 21000, name: "coventry", display_name: "Coventry", process_status: 0, processed_users: nil, statistic_users: 12, last_page: 0},
  {ang_list_id: 20130, name: "durham, united kingdom", display_name: "Durham, United Kingdom", process_status: 0, processed_users: nil, statistic_users: 6, last_page: 0},
  {ang_list_id: 17463, name: "dartford", display_name: "Dartford", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 15307, name: "kingston upon hull", display_name: "Kingston upon Hull", process_status: 0, processed_users: nil, statistic_users: 7, last_page: 0},
  {ang_list_id: 15306, name: "bradford", display_name: "Bradford", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 15217, name: "horsham", display_name: "Horsham", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 13996, name: "lancaster, united kingdom", display_name: "Lancaster, United Kingdom", process_status: 0, processed_users: nil, statistic_users: 7, last_page: 0},
  {ang_list_id: 13903, name: "norwich", display_name: "Norwich", process_status: 0, processed_users: nil, statistic_users: 16, last_page: 0},
  {ang_list_id: 13781, name: "york", display_name: "York", process_status: 0, processed_users: nil, statistic_users: 26, last_page: 0},
  {ang_list_id: 13780, name: "leeds", display_name: "Leeds", process_status: 0, processed_users: nil, statistic_users: 53, last_page: 0},
  {ang_list_id: 12163, name: "glasgow", display_name: "Glasgow", process_status: 0, processed_users: nil, statistic_users: 57, last_page: 0},
  {ang_list_id: 12031, name: "watford", display_name: "Watford", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 10278, name: "bournemouth", display_name: "Bournemouth", process_status: 0, processed_users: nil, statistic_users: 15, last_page: 0},
  {ang_list_id: 10051, name: "poole", display_name: "Poole", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 9701, name: "hatfield", display_name: "Hatfield", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 8861, name: "chesterfield", display_name: "Chesterfield", process_status: 0, processed_users: nil, statistic_users: 6, last_page: 0},
  {ang_list_id: 8839, name: "nottingham", display_name: "Nottingham", process_status: 0, processed_users: nil, statistic_users: 32, last_page: 0},
  {ang_list_id: 8807, name: "southampton", display_name: "Southampton", process_status: 0, processed_users: nil, statistic_users: 28, last_page: 0},
  {ang_list_id: 8785, name: "derby", display_name: "Derby", process_status: 0, processed_users: nil, statistic_users: 12, last_page: 0},
  {ang_list_id: 8772, name: "christchurch", display_name: "Christchurch", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 8765, name: "belfast", display_name: "Belfast", process_status: 0, processed_users: nil, statistic_users: 68, last_page: 0},
  {ang_list_id: 8724, name: "atherton", display_name: "Atherton", process_status: 0, processed_users: nil, statistic_users: 22, last_page: 0},
  {ang_list_id: 8614, name: "sunderland", display_name: "Sunderland", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 8574, name: "haverfordwest", display_name: "Haverfordwest", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 2900, name: "boston, united kingdom", display_name: "Boston, United Kingdom", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 2774, name: "bishop auckland", display_name: "Bishop Auckland", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 2604, name: "cardiff", display_name: "Cardiff", process_status: 0, processed_users: nil, statistic_users: 37, last_page: 0},
  {ang_list_id: 2603, name: "leicester", display_name: "Leicester", process_status: 0, processed_users: nil, statistic_users: 17, last_page: 0},
  {ang_list_id: 2602, name: "newcastle upon tyne", display_name: "Newcastle upon Tyne", process_status: 0, processed_users: nil, statistic_users: 73, last_page: 0},
  {ang_list_id: 2601, name: "birmingham", display_name: "Birmingham", process_status: 0, processed_users: nil, statistic_users: 105, last_page: 0},
  {ang_list_id: 2518, name: "exeter", display_name: "Exeter", process_status: 0, processed_users: nil, statistic_users: 16, last_page: 0},
  {ang_list_id: 2354, name: "oxford", display_name: "Oxford", process_status: 0, processed_users: nil, statistic_users: 143, last_page: 0},
  {ang_list_id: 2299, name: "brighton", display_name: "Brighton", process_status: 0, processed_users: nil, statistic_users: 106, last_page: 0},
  {ang_list_id: 2253, name: "peterborough", display_name: "Peterborough", process_status: 0, processed_users: nil, statistic_users: 5, last_page: 0},
  {ang_list_id: 2213, name: "sheffield", display_name: "Sheffield", process_status: 0, processed_users: nil, statistic_users: 42, last_page: 0},
  {ang_list_id: 2210, name: "edinburgh", display_name: "Edinburgh", process_status: 0, processed_users: nil, statistic_users: 147, last_page: 0},
  {ang_list_id: 2205, name: "cheltenham", display_name: "Cheltenham", process_status: 0, processed_users: nil, statistic_users: 8, last_page: 0},
  {ang_list_id: 2201, name: "guildford", display_name: "Guildford", process_status: 0, processed_users: nil, statistic_users: 16, last_page: 0},
  {ang_list_id: 2169, name: "bath", display_name: "Bath", process_status: 0, processed_users: nil, statistic_users: 23, last_page: 0},
  {ang_list_id: 2142, name: "bristol", display_name: "Bristol", process_status: 0, processed_users: nil, statistic_users: 123, last_page: 0},
  {ang_list_id: 2081, name: "shrewsbury", display_name: "Shrewsbury", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 1781, name: "manchester", display_name: "Manchester", process_status: 0, processed_users: nil, statistic_users: 175, last_page: 0},
  {ang_list_id: 1725, name: "scotland", display_name: "Scotland", process_status: 0, processed_users: nil, statistic_users: 34, last_page: 0},
  {ang_list_id: 1700, name: "cambridge", display_name: "Cambridge, UK", process_status: 0, processed_users: nil, statistic_users: 152, last_page: 0},
  {ang_list_id: 1695, name: "london", display_name: "London", process_status: 0, processed_users: nil, statistic_users: 8519, last_page: 0},
  {ang_list_id: 165060, name: "ukmerge", display_name: "Ukmerge", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 95035, name: "siauliai", display_name: "Siauliai", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 87891, name: "priekule, lithuania", display_name: "Priekule, Lithuania", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 82407, name: "klaipeda", display_name: "Klaipeda", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 81631, name: "kaunas", display_name: "Kaunas", process_status: 0, processed_users: nil, statistic_users: 16, last_page: 0},
  {ang_list_id: 1868, name: "vilnius", display_name: "Vilnius", process_status: 0, processed_users: nil, statistic_users: 135, last_page: 0},
  {ang_list_id: 179269, name: "lannion", display_name: "Lannion", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 174725, name: "angers", display_name: "Angers", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 173524, name: "la roche-sur-yon", display_name: "La Roche Sur Yon", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 172958, name: "avon, france", display_name: "Avon, France", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 170137, name: "saint-raphael", display_name: "Saint Raphael", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 168114, name: "challans", display_name: "Challans", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 167851, name: "Aubenas", display_name: "Aubenas", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 163805, name: "pau", display_name: "Pau", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 159146, name: "niort", display_name: "Niort", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 158893, name: "moissy-cramayel", display_name: "Moissy Cramayel", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 138048, name: "osny", display_name: "Osny", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 136185, name: "versailles", display_name: "Versailles", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 135961, name: "boulogne-billancourt", display_name: "Boulogne-billancourt", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 134311, name: "palaiseau", display_name: "Palaiseau", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 133483, name: "begles", display_name: "Begles", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 133254, name: "argenteuil", display_name: "Argenteuil", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 132509, name: "melun", display_name: "Melun", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 132365, name: "hyeres", display_name: "Hyeres", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 132272, name: "poissy", display_name: "Poissy", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 132174, name: "montigny-le-bretonneux", display_name: "Montigny-le-bretonneux", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 132112, name: "mantes-la-jolie", display_name: "Mantes-la-jolie", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 132088, name: "saint-etienne", display_name: "Saint-etienne", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 132070, name: "massy", display_name: "Massy", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 130123, name: "orleans", display_name: "Orleans", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 121999, name: "manosque", display_name: "Manosque", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 121610, name: "caen", display_name: "Caen", process_status: 0, processed_users: nil, statistic_users: 7, last_page: 0},
  {ang_list_id: 120043, name: "suresnes", display_name: "Suresnes", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 103220, name: "la rochelle", display_name: "La Rochelle", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 102916, name: "evry", display_name: "Evry", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 100799, name: "vitrolles", display_name: "Vitrolles", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 98527, name: "la baule-escoublac", display_name: "La Baule-escoublac", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 98064, name: "issy-les-moulineaux", display_name: "Issy-les-moulineaux", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 97803, name: "compiegne", display_name: "Compiegne", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 95984, name: "carcassonne", display_name: "Carcassonne", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 94901, name: "levallois-perret", display_name: "Levallois-perret", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 94277, name: "orsay", display_name: "Orsay", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 94107, name: "mulhouse", display_name: "Mulhouse", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 93762, name: "montreuil", display_name: "Montreuil", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 93415, name: "le havre", display_name: "Le Havre", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 89545, name: "bruges", display_name: "Bruges", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 88671, name: "neuilly-sur-seine", display_name: "Neuilly-sur-seine", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 88319, name: "clichy", display_name: "Clichy", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 86652, name: "brest, france", display_name: "Brest, France", process_status: 0, processed_users: nil, statistic_users: 8, last_page: 0},
  {ang_list_id: 85041, name: "le mans", display_name: "Le Mans", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 82169, name: "nancy", display_name: "Nancy", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 82077, name: "biarritz", display_name: "Biarritz", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 81899, name: "besancon", display_name: "Besancon", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 81881, name: "laval", display_name: "Laval", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 81609, name: "toulon", display_name: "Toulon", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 80951, name: "valbonne", display_name: "Valbonne", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 72320, name: "ajaccio", display_name: "Ajaccio", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 60016, name: "rouen", display_name: "Rouen", process_status: 0, processed_users: nil, statistic_users: 7, last_page: 0},
  {ang_list_id: 59810, name: "antibes", display_name: "Antibes", process_status: 0, processed_users: nil, statistic_users: 7, last_page: 0},
  {ang_list_id: 59758, name: "saint-denis", display_name: "Saint-denis", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 58008, name: "metz", display_name: "Metz", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 57507, name: "aix-en-provence", display_name: "Aix-en-provence", process_status: 0, processed_users: nil, statistic_users: 16, last_page: 0},
  {ang_list_id: 54106, name: "courbevoie", display_name: "Courbevoie", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 51093, name: "clermont-ferrand", display_name: "Clermont-ferrand", process_status: 0, processed_users: nil, statistic_users: 6, last_page: 0},
  {ang_list_id: 50703, name: "tours", display_name: "Tours", process_status: 0, processed_users: nil, statistic_users: 9, last_page: 0},
  {ang_list_id: 49199, name: "nantes", display_name: "Nantes", process_status: 0, processed_users: nil, statistic_users: 75, last_page: 0},
  {ang_list_id: 49149, name: "chamonix-mont-blanc", display_name: "Chamonix-mont-blanc", process_status: 0, processed_users: nil, statistic_users: 5, last_page: 0},
  {ang_list_id: 37819, name: "lorient", display_name: "Lorient", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 36036, name: "toulouse", display_name: "Toulouse", process_status: 0, processed_users: nil, statistic_users: 66, last_page: 0},
  {ang_list_id: 34056, name: "avignon", display_name: "Avignon", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 32101, name: "rennes", display_name: "Rennes", process_status: 0, processed_users: nil, statistic_users: 23, last_page: 0},
  {ang_list_id: 28488, name: "nimes", display_name: "Nimes", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 25967, name: "la teste-de-buch", display_name: "La Teste-de-buch", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 22463, name: "cannes", display_name: "Cannes", process_status: 0, processed_users: nil, statistic_users: 8, last_page: 0},
  {ang_list_id: 19929, name: "nice", display_name: "Nice", process_status: 0, processed_users: nil, statistic_users: 40, last_page: 0},
  {ang_list_id: 13795, name: "montpellier", display_name: "Montpellier", process_status: 0, processed_users: nil, statistic_users: 40, last_page: 0},
  {ang_list_id: 13077, name: "macon, france", display_name: "Macon, France", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 12588, name: "grenoble", display_name: "Grenoble", process_status: 0, processed_users: nil, statistic_users: 39, last_page: 0},
  {ang_list_id: 11964, name: "limoges", display_name: "Limoges", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 10182, name: "annecy", display_name: "Annecy", process_status: 0, processed_users: nil, statistic_users: 7, last_page: 0},
  {ang_list_id: 2668, name: "marseille", display_name: "Marseille", process_status: 0, processed_users: nil, statistic_users: 30, last_page: 0},
  {ang_list_id: 2667, name: "lyon", display_name: "Lyon", process_status: 0, processed_users: nil, statistic_users: 127, last_page: 0},
  {ang_list_id: 2666, name: "bordeaux", display_name: "Bordeaux", process_status: 0, processed_users: nil, statistic_users: 71, last_page: 0},
  {ang_list_id: 2665, name: "strasbourg", display_name: "Strasbourg", process_status: 0, processed_users: nil, statistic_users: 21, last_page: 0},
  {ang_list_id: 2146, name: "lille", display_name: "Lille", process_status: 0, processed_users: nil, statistic_users: 45, last_page: 0},
  {ang_list_id: 1842, name: "paris", display_name: "Paris", process_status: 0, processed_users: nil, statistic_users: 2407, last_page: 0},
  {ang_list_id: 176573, name: "oberursel", display_name: "Oberursel", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 176019, name: "herten", display_name: "Herten", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 175989, name: "ravensburg", display_name: "Ravensburg", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 164572, name: "ratzeburg", display_name: "Ratzeburg", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 157499, name: "simmerath", display_name: "Simmerath", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 139594, name: "landshut", display_name: "Landshut", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 135474, name: "oberhausen", display_name: "Oberhausen", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 135217, name: "kelkheim", display_name: "Kelkheim", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 134422, name: "wuppertal", display_name: "Wuppertal", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 133470, name: "jena", display_name: "Jena", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 126071, name: "bad pyrmont", display_name: "Bad Pyrmont", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 125850, name: "enger", display_name: "Enger", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 125557, name: "brandenburg", display_name: "Brandenburg", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 124024, name: "ludinghausen", display_name: "Ludinghausen", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 118882, name: "grenzach-wyhlen", display_name: "Grenzach-wyhlen", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 117892, name: "kempten", display_name: "Kempten", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 116636, name: "heilbronn", display_name: "Heilbronn", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 114144, name: "lahr", display_name: "Lahr", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 113919, name: "sinsheim", display_name: "Sinsheim", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 113350, name: "werl", display_name: "Werl", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 112872, name: "reutlingen", display_name: "Reutlingen", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 110589, name: "lilienthal", display_name: "Lilienthal", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 109870, name: "ingolstadt", display_name: "Ingolstadt", process_status: 0, processed_users: nil, statistic_users: 5, last_page: 0},
  {ang_list_id: 108397, name: "porta westfalica", display_name: "Porta Westfalica", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 102204, name: "tubingen", display_name: "Tubingen", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 101647, name: "leverkusen", display_name: "Leverkusen", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 99464, name: "pasewalk", display_name: "Pasewalk", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 99230, name: "ratisbon", display_name: "Ratisbon", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 96246, name: "kassel", display_name: "Kassel", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 94353, name: "starnberg", display_name: "Starnberg", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 93602, name: "wulfrath", display_name: "Wulfrath", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 93054, name: "uberlingen", display_name: "Uberlingen", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 93048, name: "germering", display_name: "Germering", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 92727, name: "warburg", display_name: "Warburg", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 92482, name: "bottrop", display_name: "Bottrop", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 90949, name: "lemgo", display_name: "Lemgo", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 90051, name: "wurzburg", display_name: "Wurzburg", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 88839, name: "gottingen", display_name: "Gottingen", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 87699, name: "bergen, germany", display_name: "Bergen, Germany", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 87225, name: "vallendar", display_name: "Vallendar", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 86891, name: "ochsenfurt", display_name: "Ochsenfurt", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 86512, name: "witten", display_name: "Witten", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 85954, name: "luneburg", display_name: "Luneburg", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 85778, name: "halle, germany", display_name: "Halle, Germany", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 85355, name: "rostock", display_name: "Rostock", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 85150, name: "bielefeld", display_name: "Bielefeld", process_status: 0, processed_users: nil, statistic_users: 8, last_page: 0},
  {ang_list_id: 83798, name: "monchengladbach", display_name: "Monchengladbach", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 83797, name: "passau", display_name: "Passau", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 83788, name: "taunusstein", display_name: "Taunusstein", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 83725, name: "mulheim", display_name: "Mulheim", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 83616, name: "baden-baden", display_name: "Baden-baden", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 83566, name: "bremen", display_name: "Bremen", process_status: 0, processed_users: nil, statistic_users: 15, last_page: 0},
  {ang_list_id: 83292, name: "olpe", display_name: "Olpe", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 82670, name: "wismar", display_name: "Wismar", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 82087, name: "aachen", display_name: "Aachen", process_status: 0, processed_users: nil, statistic_users: 16, last_page: 0},
  {ang_list_id: 81766, name: "mainz", display_name: "Mainz", process_status: 0, processed_users: nil, statistic_users: 10, last_page: 0},
  {ang_list_id: 81028, name: "oldenburg", display_name: "Oldenburg", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 80921, name: "pforzheim", display_name: "Pforzheim", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 80810, name: "stein, germany", display_name: "Stein, Germany", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 79812, name: "koblenz", display_name: "Koblenz", process_status: 0, processed_users: nil, statistic_users: 5, last_page: 0},
  {ang_list_id: 72660, name: "erfurt", display_name: "Erfurt", process_status: 0, processed_users: nil, statistic_users: 1, last_page: 0},
  {ang_list_id: 71222, name: "bamberg", display_name: "Bamberg", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 59372, name: "wiesbaden", display_name: "Wiesbaden", process_status: 0, processed_users: nil, statistic_users: 5, last_page: 0},
  {ang_list_id: 58973, name: "chemnitz", display_name: "Chemnitz", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 58352, name: "trier", display_name: "Trier", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 57420, name: "augsburg", display_name: "Augsburg", process_status: 0, processed_users: nil, statistic_users: 2, last_page: 0},
  {ang_list_id: 54658, name: "friedrichshafen", display_name: "Friedrichshafen", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 53870, name: "paderborn", display_name: "Paderborn", process_status: 0, processed_users: nil, statistic_users: 8, last_page: 0},
  {ang_list_id: 53729, name: "konstanz", display_name: "Konstanz", process_status: 0, processed_users: nil, statistic_users: 6, last_page: 0},
  {ang_list_id: 47925, name: "ulm", display_name: "Ulm", process_status: 0, processed_users: nil, statistic_users: 9, last_page: 0},
  {ang_list_id: 45664, name: "aschaffenburg", display_name: "Aschaffenburg", process_status: 0, processed_users: nil, statistic_users: 3, last_page: 0},
  {ang_list_id: 45640, name: "konigstein", display_name: "Konigstein", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 42962, name: "hanover", display_name: "Hanover", process_status: 0, processed_users: nil, statistic_users: 25, last_page: 0},
  {ang_list_id: 39668, name: "potsdam", display_name: "Potsdam", process_status: 0, processed_users: nil, statistic_users: 11, last_page: 0},
  {ang_list_id: 34785, name: "erlangen", display_name: "Erlangen", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 34086, name: "landsberg", display_name: "Landsberg", process_status: 0, processed_users: nil, statistic_users: 0, last_page: 0},
  {ang_list_id: 31504, name: "kiel", display_name: "Kiel", process_status: 0, processed_users: nil, statistic_users: 7, last_page: 0},
  {ang_list_id: 30004, name: "freiburg", display_name: "Freiburg", process_status: 0, processed_users: nil, statistic_users: 6, last_page: 0},
  {ang_list_id: 28121, name: "leipzig", display_name: "Leipzig", process_status: 0, processed_users: nil, statistic_users: 24, last_page: 0},
  {ang_list_id: 20689, name: "essen", display_name: "Essen", process_status: 0, processed_users: nil, statistic_users: 10, last_page: 0},
  {ang_list_id: 14519, name: "dresden", display_name: "Dresden", process_status: 0, processed_users: nil, statistic_users: 27, last_page: 0},
  {ang_list_id: 11079, name: "bochum", display_name: "Bochum", process_status: 0, processed_users: nil, statistic_users: 4, last_page: 0},
  {ang_list_id: 10957, name: "munster, germany", display_name: "Munster, Germany", process_status: 0, processed_users: nil, statistic_users: 11, last_page: 0},
  {ang_list_id: 10852, name: "bonn", display_name: "Bonn", process_status: 0, processed_users: nil, statistic_users: 29, last_page: 0},
  {ang_list_id: 10684, name: "dusseldorf", display_name: "Dusseldorf", process_status: 0, processed_users: nil, statistic_users: 65, last_page: 0},
  {ang_list_id: 9083, name: "kaiserslautern", display_name: "Kaiserslautern", process_status: 0, processed_users: nil, statistic_users: 5, last_page: 0},
  {ang_list_id: 8918, name: "darmstadt", display_name: "Darmstadt", process_status: 0, processed_users: nil, statistic_users: 9, last_page: 0},
  {ang_list_id: 8860, name: "nuremberg", display_name: "Nuremberg", process_status: 0, processed_users: nil, statistic_users: 14, last_page: 0},
  {ang_list_id: 8808, name: "mannheim", display_name: "Mannheim", process_status: 0, processed_users: nil, statistic_users: 15, last_page: 0},
  {ang_list_id: 8727, name: "heidelberg", display_name: "Heidelberg", process_status: 0, processed_users: nil, statistic_users: 25, last_page: 0},
  {ang_list_id: 3087, name: "dortmund", display_name: "Dortmund", process_status: 0, processed_users: nil, statistic_users: 18, last_page: 0},
  {ang_list_id: 2669, name: "stuttgart", display_name: "Stuttgart", process_status: 0, processed_users: nil, statistic_users: 79, last_page: 0},
  {ang_list_id: 2464, name: "cologne", display_name: "Cologne", process_status: 0, processed_users: nil, statistic_users: 200, last_page: 0},
  {ang_list_id: 2422, name: "brunswick", display_name: "Brunswick", process_status: 0, processed_users: nil, statistic_users: 7, last_page: 0},
  {ang_list_id: 2128, name: "munich", display_name: "Munich", process_status: 0, processed_users: nil, statistic_users: 552, last_page: 0},
  {ang_list_id: 2087, name: "karlsruhe", display_name: "Karlsruhe", process_status: 0, processed_users: nil, statistic_users: 32, last_page: 0},
  {ang_list_id: 1915, name: "hamburg", display_name: "Hamburg", process_status: 0, processed_users: nil, statistic_users: 282, last_page: 0},
  {ang_list_id: 1914, name: "berlin", display_name: "Berlin", process_status: 0, processed_users: nil, statistic_users: 2137, last_page: 0},
  {ang_list_id: 1865, name: "frankfurt", display_name: "Frankfurt", process_status: 0, processed_users: nil, statistic_users: 134, last_page: 0},
  {ang_list_id: 10700, name: "tartu", display_name: "Tartu", process_status: 0, processed_users: nil, statistic_users: 28, last_page: 0},
  {ang_list_id: 2423, name: "tallinn", display_name: "Tallinn", process_status: 0, processed_users: nil, statistic_users: 207, last_page: 0}
])
